### ISSUE TITLE
Relicense?

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-datastore-kvstore#210]
@zamnuts pointed out this repo is still MIT. Do we have licensing robots that could take aim on this repo to update as necessary for Apache-2? The ‘LICENSE’ file, as well as package.json and samples/package.json still are MIT.

@JustinBeckwith

**Comment by JustinBeckwith** [comment]
We don't have a robot that does it, but sure!  OSPO has approved these kinds of things in the past, so no big deal.  Guessing we need to remove an ignore in `synth.py`, and update the README/package.json and all the headers.
